---
# create kafka server and client instances
- name: create kafka instances
  hosts: localhost
  vars_files:
      - group_vars/kafka/vars
  
  vars:
    count: '{{ cluster_size - 1 }}'

  tasks:

  # generate playbook secrets
  - name: generating playbook secrets
    lineinfile:
      insertafter: EOF
      path: group_vars/kafka/vars
      line: |
        truststore_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
        keystore_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
        key_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
        ca_password: "{{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits,punctuation') }}"
        pkcs12_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
        sudo_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
    no_log: true

  - name: creating kafka servers
    linode.cloud.instance:
      label: '{{ instance_prefix }}{{ item | int + 1 }}-{{ uuid }}'
      api_token: '{{ token }}'
      type: '{{ type }}'
      region: '{{ region }}'
      image: '{{ image }}'
      root_pass: '{{ root_pass }}'
      authorized_keys: '{{ ssh_keys }}'
      private_ip: true
      #stackscript_id: null
      #ua_prefix: 'marketplace-kafka-occ'          
      tags: '{{ linode_tags }}'
      state: present
    with_sequence: count='{{ count }}'

  - name: get info about the instances
    linode.cloud.instance_info:
      api_token: '{{ token }}'
      label: '{{ instance_prefix }}{{ item }}-{{ uuid }}'
    register: info
    with_sequence: count='{{ cluster_size }}'

  - name: update group_vars
    blockinfile:
      path: ./group_vars/kafka/vars
      marker: "# {mark} INSTANCE VARS"
      block: |
        #jinja2: trim_blocks:False
        kafka_data:
          server:
            {%- for count in range(cluster_size) %}
            - kafka{{ count + 1 }}:
              instance:
                hostname: kafka{{ count + 1 }}
                ip_pub1: {{ info.results[count].instance.ipv4[0] }}
                ip_priv1: {{ info.results[count].instance.ipv4[1] }}
            {%- endfor %}

  - name: add kafka nodes to inventory
    blockinfile:
      path: ./hosts
      marker: "# {mark} KAFKA INSTANCES"
      block: |
        #jinja2: trim_blocks:False
        [kafka]
        localhost ansible_connection=local user=root role='controller and broker'
        {%- for count in range(cluster_size - 1) %}
        {{ info.results[count + 1].instance.ipv4[0] }} {% if count < controller_count - 1 %}role='controller and broker'{%else%}role='broker only'{%endif%}
        {%- endfor %}

  - name: wait for port 22 to become open
    wait_for:
      port: 22
      host: '{{ item.instance.ipv4[0] }}'
      search_regex: OpenSSH
      delay: 10
    connection: local
    with_items: "{{ info.results }}"