---
# configure kafka
- name: configure kafka servers
  hosts: kafka
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/kafka/vars
  tasks:
   - name: creating sudo user
     import_task: roles/post/tasks/sudouser.yml
  roles:
    - common
    - kafka
    - post
