---
# main

- name: configure hostname
  import_tasks: hostname.yml
  tags: test

- name: create kafka user
  import_tasks: user.yml
  tags: test

- name: installing kafka
  import_tasks: install.yml
  tags: test

- name: configure cluster certs
  import_tasks: ssl.yml
  tags: test

- name: configure kafka
  import_tasks: configure.yml
  tags: test