---
# create kafka system user and group

- name: create kafka group
  group:
    name: kafka
    state: present
    system: true

- name: create kafka user
  user:
    name: kafka
    shell: /sbin/nologin
    expires: -1
    create_home: false
    system: true
    state: present