---
# motd and creds gen
- name: copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: writing creds into file
  copy:
    dest: "/home/{{ sudo_username }}/.credentials"
    mode: '0600'
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    content: |
      sudo username: {{ sudo_username }}
      sudo password: {{ sudo_password }}
      truststore_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
      keystore_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
      key_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
      ca_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}
      pkcs12_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}     